### ISSUE TITLE
Updating opportunities doesn't work

### ISSUE THREAD

**Issue by rvanlooijen** [redmantech/Mautic_CRM#1]
Updating opportunities does not work. After saving, the list shows the updated values and an 'opportunity is updated' popup is shown, but if I refresh the page all fields return to their previous value.

Hi, btw.: First off, fantastic work! We're trying Mautic and we were missing exactly what your plugins add. I do have a few remarks that may help you improve it, and will create issues for them here. It would be absolutely great if you can fix those, and I think it should be added to default Mautic.

**Comment by robertoamoreno** [comment]
I am not able to reproduce this can you provide more details

**Comment by rvanlooijen** [comment]
After some digging I found that the issue seems to be caused by OpportunityModel.php line 47:

public function saveEntity($entity, $unlock = true)
    {
        if ($entity->getId()) {
            $this->em->flush();
            //return;
        }

If I comment the return, the entity actually gets saved when editing.
