### ISSUE TITLE
Does this work on 2.0?

### ISSUE THREAD

**Issue by 3ruce** [redmantech/Mautic_CRM#13]
This looks like a great plugin but does it work in Mautic 2.0?

**Comment by 3ruce** [comment]
It doesn't look like it...

`Strict Standards: Declaration of MauticPlugin\CustomCrmBundle\CustomCrmBundle::onPluginInstall() should be compatible with Mautic\PluginBundle\Bundle\PluginBundleBase::onPluginInstall(Mautic\PluginBundle\Entity\Plugin $plugin, Mautic\CoreBundle\Factory\MauticFactory $factory, $metadata = NULL, $installedSchema = NULL) in /home/mautic/plugins/CustomCrmBundle/CustomCrmBundle.php on line 31`

**Comment by danionut90** [comment]
@3ruce Plugin was updated and works with version 2 now.

**Comment by 3ruce** [comment]
Thank you!
